
USE cards
GO

CREATE TABLE CapturedText(
	CapturedTextId	INT					IDENTITY(1,1)		PRIMARY KEY,
	[Text]			NVARCHAR(1000)		NOT NULL,
	dtAdded			DATETIME			NOT NULL			DEFAULT GETDATE(),
	dtUpdated		DATETIME			NOT NULL			DEFAULT GETDATE()
)

